env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "quotes": ["error", "double"],
  "require-jsdoc": 0
}
root: true
